# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.srcs/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/design_citireSD_axi_smc_0.xci
# IP: The module: 'design_citireSD_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/bd_c60d.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_0/bd_c60d_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_1/bd_c60d_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_2/bd_c60d_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_3/bd_c60d_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_4/bd_c60d_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_5/bd_c60d_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_6/bd_c60d_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_7/bd_c60d_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_8/bd_c60d_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_9/bd_c60d_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_10/bd_c60d_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_11/bd_c60d_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_12/bd_c60d_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_13/bd_c60d_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_14/bd_c60d_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_15/bd_c60d_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_16/bd_c60d_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_17/bd_c60d_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_18/bd_c60d_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_19/bd_c60d_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_20/bd_c60d_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_21/bd_c60d_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_22/bd_c60d_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_23/bd_c60d_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_24/bd_c60d_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_25/bd_c60d_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_26/bd_c60d_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_27/bd_c60d_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_28/bd_c60d_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_29/bd_c60d_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_30/bd_c60d_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_31/bd_c60d_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_32/bd_c60d_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_33/bd_c60d_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_34/bd_c60d_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_35/bd_c60d_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_36/bd_c60d_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_37/bd_c60d_m03s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_38/bd_c60d_m03arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_39/bd_c60d_m03rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_40/bd_c60d_m03awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_41/bd_c60d_m03wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_42/bd_c60d_m03bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_43/bd_c60d_m03e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_44/bd_c60d_m04s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_45/bd_c60d_m04arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_46/bd_c60d_m04rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_47/bd_c60d_m04awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_48/bd_c60d_m04wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_49/bd_c60d_m04bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_50/bd_c60d_m04e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_51/bd_c60d_m05s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_52/bd_c60d_m05arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_53/bd_c60d_m05rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_54/bd_c60d_m05awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_55/bd_c60d_m05wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_56/bd_c60d_m05bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_57/bd_c60d_m05e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_1/bd_c60d_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_1/bd_c60d_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_2/bd_c60d_arsw_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_3/bd_c60d_rsw_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_4/bd_c60d_awsw_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_5/bd_c60d_wsw_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_6/bd_c60d_bsw_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_10/bd_c60d_s00a2s_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_11/bd_c60d_sarn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_11/bd_c60d_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_12/bd_c60d_srn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_12/bd_c60d_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_13/bd_c60d_sawn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_13/bd_c60d_sawn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_14/bd_c60d_swn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_14/bd_c60d_swn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_15/bd_c60d_sbn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_15/bd_c60d_sbn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_16/bd_c60d_m00s2a_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_17/bd_c60d_m00arn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_17/bd_c60d_m00arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_18/bd_c60d_m00rn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_18/bd_c60d_m00rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_19/bd_c60d_m00awn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_19/bd_c60d_m00awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_20/bd_c60d_m00wn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_20/bd_c60d_m00wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_21/bd_c60d_m00bn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_21/bd_c60d_m00bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_23/bd_c60d_m01s2a_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_24/bd_c60d_m01arn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_24/bd_c60d_m01arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_25/bd_c60d_m01rn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_25/bd_c60d_m01rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_26/bd_c60d_m01awn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_26/bd_c60d_m01awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_27/bd_c60d_m01wn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_27/bd_c60d_m01wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_28/bd_c60d_m01bn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_28/bd_c60d_m01bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_30/bd_c60d_m02s2a_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_31/bd_c60d_m02arn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_31/bd_c60d_m02arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_32/bd_c60d_m02rn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_32/bd_c60d_m02rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_33/bd_c60d_m02awn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_33/bd_c60d_m02awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_34/bd_c60d_m02wn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_34/bd_c60d_m02wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_35/bd_c60d_m02bn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_35/bd_c60d_m02bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_37/bd_c60d_m03s2a_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_38/bd_c60d_m03arn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_38/bd_c60d_m03arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_39/bd_c60d_m03rn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_39/bd_c60d_m03rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_40/bd_c60d_m03awn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_40/bd_c60d_m03awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_41/bd_c60d_m03wn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_41/bd_c60d_m03wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_42/bd_c60d_m03bn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_42/bd_c60d_m03bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_44/bd_c60d_m04s2a_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_45/bd_c60d_m04arn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_45/bd_c60d_m04arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_46/bd_c60d_m04rn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_46/bd_c60d_m04rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_47/bd_c60d_m04awn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_47/bd_c60d_m04awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_48/bd_c60d_m04wn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_48/bd_c60d_m04wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_49/bd_c60d_m04bn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_49/bd_c60d_m04bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_51/bd_c60d_m05s2a_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_52/bd_c60d_m05arn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_52/bd_c60d_m05arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_53/bd_c60d_m05rn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_53/bd_c60d_m05rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_54/bd_c60d_m05awn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_54/bd_c60d_m05awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_55/bd_c60d_m05wn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_55/bd_c60d_m05wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_56/bd_c60d_m05bn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_56/bd_c60d_m05bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_citireSD_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_citireSD_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.srcs/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/design_citireSD_axi_smc_0.xci
# IP: The module: 'design_citireSD_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/bd_c60d.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_0/bd_c60d_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_1/bd_c60d_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_2/bd_c60d_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_3/bd_c60d_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_4/bd_c60d_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_5/bd_c60d_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_6/bd_c60d_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_7/bd_c60d_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_8/bd_c60d_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_9/bd_c60d_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_10/bd_c60d_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_11/bd_c60d_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_12/bd_c60d_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_13/bd_c60d_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_14/bd_c60d_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_15/bd_c60d_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_16/bd_c60d_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_17/bd_c60d_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_18/bd_c60d_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_19/bd_c60d_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_20/bd_c60d_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_21/bd_c60d_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_22/bd_c60d_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_23/bd_c60d_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_24/bd_c60d_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_25/bd_c60d_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_26/bd_c60d_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_27/bd_c60d_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_28/bd_c60d_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_29/bd_c60d_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_30/bd_c60d_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_31/bd_c60d_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_32/bd_c60d_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_33/bd_c60d_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_34/bd_c60d_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_35/bd_c60d_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_36/bd_c60d_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_37/bd_c60d_m03s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_38/bd_c60d_m03arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_39/bd_c60d_m03rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_40/bd_c60d_m03awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_41/bd_c60d_m03wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_42/bd_c60d_m03bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_43/bd_c60d_m03e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_44/bd_c60d_m04s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_45/bd_c60d_m04arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_46/bd_c60d_m04rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_47/bd_c60d_m04awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_48/bd_c60d_m04wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_49/bd_c60d_m04bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_50/bd_c60d_m04e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_51/bd_c60d_m05s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_52/bd_c60d_m05arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_53/bd_c60d_m05rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_54/bd_c60d_m05awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_55/bd_c60d_m05wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_56/bd_c60d_m05bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_57/bd_c60d_m05e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_1/bd_c60d_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_1/bd_c60d_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_2/bd_c60d_arsw_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_3/bd_c60d_rsw_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_4/bd_c60d_awsw_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_5/bd_c60d_wsw_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_6/bd_c60d_bsw_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_10/bd_c60d_s00a2s_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_11/bd_c60d_sarn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_11/bd_c60d_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_12/bd_c60d_srn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_12/bd_c60d_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_13/bd_c60d_sawn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_13/bd_c60d_sawn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_14/bd_c60d_swn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_14/bd_c60d_swn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_15/bd_c60d_sbn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_15/bd_c60d_sbn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_16/bd_c60d_m00s2a_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_17/bd_c60d_m00arn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_17/bd_c60d_m00arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_18/bd_c60d_m00rn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_18/bd_c60d_m00rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_19/bd_c60d_m00awn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_19/bd_c60d_m00awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_20/bd_c60d_m00wn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_20/bd_c60d_m00wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_21/bd_c60d_m00bn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_21/bd_c60d_m00bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_23/bd_c60d_m01s2a_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_24/bd_c60d_m01arn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_24/bd_c60d_m01arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_25/bd_c60d_m01rn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_25/bd_c60d_m01rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_26/bd_c60d_m01awn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_26/bd_c60d_m01awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_27/bd_c60d_m01wn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_27/bd_c60d_m01wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_28/bd_c60d_m01bn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_28/bd_c60d_m01bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_30/bd_c60d_m02s2a_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_31/bd_c60d_m02arn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_31/bd_c60d_m02arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_32/bd_c60d_m02rn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_32/bd_c60d_m02rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_33/bd_c60d_m02awn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_33/bd_c60d_m02awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_34/bd_c60d_m02wn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_34/bd_c60d_m02wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_35/bd_c60d_m02bn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_35/bd_c60d_m02bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_37/bd_c60d_m03s2a_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_38/bd_c60d_m03arn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_38/bd_c60d_m03arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_39/bd_c60d_m03rn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_39/bd_c60d_m03rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_40/bd_c60d_m03awn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_40/bd_c60d_m03awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_41/bd_c60d_m03wn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_41/bd_c60d_m03wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_42/bd_c60d_m03bn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_42/bd_c60d_m03bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_44/bd_c60d_m04s2a_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_45/bd_c60d_m04arn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_45/bd_c60d_m04arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_46/bd_c60d_m04rn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_46/bd_c60d_m04rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_47/bd_c60d_m04awn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_47/bd_c60d_m04awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_48/bd_c60d_m04wn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_48/bd_c60d_m04wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_49/bd_c60d_m04bn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_49/bd_c60d_m04bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_51/bd_c60d_m05s2a_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_52/bd_c60d_m05arn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_52/bd_c60d_m05arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_53/bd_c60d_m05rn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_53/bd_c60d_m05rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_54/bd_c60d_m05awn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_54/bd_c60d_m05awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_55/bd_c60d_m05wn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_55/bd_c60d_m05wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_56/bd_c60d_m05bn_0_ooc.xdc

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/bd_0/ip/ip_56/bd_c60d_m05bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_citireSD_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_citireSD_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
