# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_citireSD/design_citireSD.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_citireSD || ORIG_REF_NAME==design_citireSD} -quiet] -quiet

# IP: bd/design_citireSD/ip/design_citireSD_processing_system7_0_0/design_citireSD_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_citireSD_processing_system7_0_0 || ORIG_REF_NAME==design_citireSD_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_citireSD/ip/design_citireSD_axi_bram_ctrl_0_0/design_citireSD_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_citireSD_axi_bram_ctrl_0_0 || ORIG_REF_NAME==design_citireSD_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/design_citireSD/ip/design_citireSD_axi_bram_ctrl_1_0/design_citireSD_axi_bram_ctrl_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_citireSD_axi_bram_ctrl_1_0 || ORIG_REF_NAME==design_citireSD_axi_bram_ctrl_1_0} -quiet] -quiet

# IP: bd/design_citireSD/ip/design_citireSD_axi_bram_ctrl_2_0/design_citireSD_axi_bram_ctrl_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_citireSD_axi_bram_ctrl_2_0 || ORIG_REF_NAME==design_citireSD_axi_bram_ctrl_2_0} -quiet] -quiet

# IP: bd/design_citireSD/ip/design_citireSD_axi_bram_ctrl_3_0/design_citireSD_axi_bram_ctrl_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_citireSD_axi_bram_ctrl_3_0 || ORIG_REF_NAME==design_citireSD_axi_bram_ctrl_3_0} -quiet] -quiet

# IP: bd/design_citireSD/ip/design_citireSD_axi_gpio_0_0/design_citireSD_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_citireSD_axi_gpio_0_0 || ORIG_REF_NAME==design_citireSD_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_citireSD/ip/design_citireSD_axi_gpio_1_0/design_citireSD_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_citireSD_axi_gpio_1_0 || ORIG_REF_NAME==design_citireSD_axi_gpio_1_0} -quiet] -quiet

# IP: bd/design_citireSD/ip/design_citireSD_axi_smc_0/design_citireSD_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_citireSD_axi_smc_0 || ORIG_REF_NAME==design_citireSD_axi_smc_0} -quiet] -quiet

# IP: bd/design_citireSD/ip/design_citireSD_rst_ps7_0_50M_0/design_citireSD_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_citireSD_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_citireSD_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/design_citireSD_ooc.xdc
