# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.srcs/sources_1/bd/design_citireSD/ip/design_citireSD_processing_system7_0_0/design_citireSD_processing_system7_0_0.xci
# IP: The module: 'design_citireSD_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_processing_system7_0_0/design_citireSD_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_citireSD_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.srcs/sources_1/bd/design_citireSD/ip/design_citireSD_processing_system7_0_0/design_citireSD_processing_system7_0_0.xci
# IP: The module: 'design_citireSD_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ssc/PROIECT/vivado/Citire_SD/Citire_SD.gen/sources_1/bd/design_citireSD/ip/design_citireSD_processing_system7_0_0/design_citireSD_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_citireSD_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
